### PR TITLE
[WIP] Major refactoring

### PR DESCRIPTION
**Pull request by andreamattavelli**
This pull request attempts to better organize the code and automatize the build of SUSHI.

Some comments:
1. I've incorporated the code of sushi and sushi-lib. They are now referred to as `master` and `runtime`.
2. I've also incorporated JBSE as git submodule, since SUSHI is closely linked to it.
3. I've created a Maven pom.xml to build the projects.

This PR depends on https://github.com/pietrobraione/jbse/pull/8

### CODE REVIEW

**Comment by pietrobraione** [comment]
OK for the general idea, but I would like not to lose the history of the sushi-lib project, so I would leave it in its own repository and incorporate it as a submodule.

**Comment by andreamattavelli** [comment]
@pietrobraione Done.
This PR now depends on https://github.com/pietrobraione/sushi-lib/pull/2 and cannot be merged until then.

**Comment by pietrobraione** [comment]
Reckon you should bump sushi-lib version before merging...

**Comment by andreamattavelli** [comment]
> Reckon you should bump sushi-lib version before merging...

Absolutely, otherwise the build will fail since sushi-lib does not have Maven support.
Another point to solve before merging IMHO is https://github.com/pietrobraione/jbse/issues/10. Otherwise `mvn package` will fail.

**Comment by pietrobraione** [comment]
Ack.

**Pull request merged**
